import {NextRequest,NextResponse} from 'next/server';
import {action,catalog,identity,admin,settings,StoreError} from '@/lib/store';
import {rows,one,runtime} from '@/lib/server';
import {ZodError} from 'zod';
export const dynamic='force-dynamic';
export async function GET(req:NextRequest){try{const view=req.nextUrl.searchParams.get('view')||'catalog';if(view==='catalog')return NextResponse.json({products:await catalog(),categories:await rows('SELECT * FROM categories'),collections:await rows('SELECT * FROM collections'),settings:await settings(),banners:await rows('SELECT * FROM banners WHERE active=1')});if(view==='reviews')return NextResponse.json(await rows("SELECT r.id,r.rating,r.body,r.image,r.created,u.name FROM reviews r JOIN users u ON u.id=r.user WHERE r.product=? AND r.status='approved'",req.nextUrl.searchParams.get('product')));const u=await identity();if(view==='account'){const orders=await rows('SELECT * FROM orders WHERE user=? ORDER BY created DESC',u.userId);for(const o of orders)o.items=await rows('SELECT * FROM order_items WHERE order_id=?',o.id);return NextResponse.json({user:await one('SELECT * FROM users WHERE id=?',u.userId),admin:u.admin,cart:await rows('SELECT * FROM cart WHERE user=?',u.userId),wishlist:await rows('SELECT * FROM wishlists WHERE user=?',u.userId),orders,online_ready:Boolean(runtime('RAZORPAY_KEY_ID')&&runtime('RAZORPAY_KEY_SECRET'))});}await admin();if(view==='admin'){const tables=['products','categories','collections','coupons','banners','orders','users','reviews','messages','notifications'];const result:any={};for(const t of tables)result[t]=await rows(`SELECT * FROM ${t}`);result.settings=await settings();return NextResponse.json(result);}throw new StoreError('Not found.',404);}catch(e){return failure(e)}}
export async function POST(req:NextRequest){try{if(req.headers.get('origin')!==req.nextUrl.origin)throw new StoreError('Refresh the page and try again.',403);if(Number(req.headers.get('content-length')||0)>100000)throw new StoreError('The request is too large.',413);const data:any=await req.json();return NextResponse.json(await action(data.action,data.input||{}));}catch(e){return failure(e)}}
function failure(e:unknown){if(e instanceof StoreError)return NextResponse.json({error:e.message},{status:e.status});if(e instanceof ZodError)return NextResponse.json({error:e.issues[0]?.message||'Please check your entries.'},{status:400});console.error('Store request failed',e instanceof Error?e.message:'Unknown error');return NextResponse.json({error:'The store could not complete this request. Please try again.'},{status:503});}

