const KEY='anime-kingdom-html-demo-v1',E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),INR=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n);
const defaults=[['gojo','Gojo Satoru Figure','Jujutsu Kaisen',999,12],['spider','Spider-Man Display Figure','Superheroes',1199,8],['hulk','Red Hulk Collectible','Superheroes',1299,5]].map(([id,name,anime,price,stock],i)=>({id,name,anime,price,stock,original:0,image:id,category:i===3?'Custom 3D Figures':i===0?'Anime Figures':'Collectibles',new:i===1||i===2,featured:true,material:'Not specified',height:i===0||i===2?23:i===1?20:0,description:'Character collectible for your display shelf. Contact Anime Kingdom for availability and product details.'}));
defaults.push({"id":"pikachu","name":"Pikachu Figure","anime":"Pokémon","price":1299,"original":0,"stock":1,"availabilityUnconfirmed":true,"image":"pikachu1","images":["pikachu1","pikachu2","pikachu3","pikachu4"],"category":"Anime Figures","new":true,"featured":true,"material":"Not specified","height":23,"description":"A cheerful Pikachu display figure with a waving pose and signature lightning-bolt tail. Height: 23 cm. Browse all four product photos. Availability is confirmed by the seller."});
defaults.push({"id":"ganesha","name":"Ganesha Statue","anime":"Spiritual Decor","price":1199,"original":0,"stock":1,"availabilityUnconfirmed":true,"image":"ganesha","images":["ganesha"],"category":"Home & Desk","new":true,"featured":true,"material":"Not specified","height":23,"description":"An orange Ganesha statue for your home or display space. Height: 23 cm. Availability is confirmed by the seller."});
defaults.push({"id":"bookstand","name":"Honeycomb Book Stand","anime":"Home & Desk","price":499,"original":0,"stock":1,"availabilityUnconfirmed":true,"image":"bookstand1","images":["bookstand1","bookstand2"],"category":"Home & Desk","new":true,"featured":true,"material":"Not specified","height":0,"description":"A black book stand with a honeycomb design and front page holders for your reading space. Browse both product photos. Availability is confirmed by the seller."});
defaults.push({"id":"krishna","name":"Krishna Statue","anime":"Spiritual Decor","price":999,"original":0,"stock":20,"availabilityUnconfirmed":false,"image":"krishna1","images":["krishna1","krishna2"],"category":"Home & Desk","new":true,"featured":true,"material":"Not specified","height":20,"description":"A Krishna statue holding a flute, with a detailed crown and lotus base. Height: 20 cm. Browse both product photos."});
for(const p of defaults){p.stock=20;p.availabilityUnconfirmed=false;}
defaults.push({"id":"heart","name":"Heart Keychain","anime":"Accessories","price":999,"original":0,"stock":20,"packSize":20,"availabilityUnconfirmed":false,"image":"heart1","images":["heart1","heart2"],"category":"Accessories","new":true,"featured":true,"height":0,"description":"Red lattice heart keychain. Price: ₹999 per pack of 20 pieces. Minimum order: 1 pack."});
let state={products:structuredClone(defaults),cart:{},wishlist:[],orders:[],requests:[],profile:{},dropDate:'',policies:{}};try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.products))state={...state,...s}}catch{}
// Apply confirmed catalog changes without removing customer carts or orders.
const catalogRevision='2026-09-14-prices';
if(state.catalogRevision!==catalogRevision){
  for(const fresh of defaults){const saved=state.products.find(p=>p.id===fresh.id);if(saved)Object.assign(saved,{price:fresh.price,original:0,height:fresh.height,description:fresh.description});else state.products.push(structuredClone(fresh));}
  state.catalogRevision=catalogRevision;
}
// Replace the old Gojo photograph in previously saved catalogs too.
if(state.gojoPhotoRevision!=='studio-photo-1'){const p=state.products.find(p=>p.id==='gojo');if(p){p.image='gojo';p.images=['gojo'];}state.gojoPhotoRevision='studio-photo-1';}
if(!state.products.some(p=>p.id==='pikachu'))state.products.push(structuredClone(defaults.find(p=>p.id==='pikachu')));
if(!state.products.some(p=>p.id==='ganesha'))state.products.push(structuredClone(defaults.find(p=>p.id==='ganesha')));
if(!state.products.some(p=>p.id==='bookstand'))state.products.push(structuredClone(defaults.find(p=>p.id==='bookstand')));
if(state.stockRevision!=='2026-09-15-20-pieces'){for(const p of state.products){p.stock=20;p.availabilityUnconfirmed=false;}state.stockRevision='2026-09-15-20-pieces';}
if(!state.products.some(p=>p.id==='krishna'))state.products.push(structuredClone(defaults.find(p=>p.id==='krishna')));
if(!state.products.some(p=>p.id==='heart'))state.products.push(structuredClone(defaults.find(p=>p.id==='heart')));
if(state.heartStockRevision!==1){Object.assign(state.products.find(p=>p.id==='heart'),{stock:400,minQty:20});state.heartStockRevision=1;}
if(state.heartPackRevision!==1){const p=state.products.find(p=>p.id==='heart');Object.assign(p,{price:999,stock:20,packSize:20,description:'Red lattice heart keychain. Pack of 20 pieces for ₹999. Minimum order: 1 pack.'});delete p.minQty;if(state.cart.heart)state.cart.heart=Math.min(20,Math.ceil(state.cart.heart/20));state.heartPackRevision=1;}
if(state.hulkHeightRevision!==1){const p=state.products.find(p=>p.id==='hulk');if(p)p.height=23;state.hulkHeightRevision=1;}
if(state.heartPhotoDescriptionRevision!==1){const p=state.products.find(p=>p.id==='heart');if(p)Object.assign(p,{"image":"heart1","images":["heart1","heart2"],"description":"Red lattice heart keychain that can also be filled with toffees and chocolates for gifting. Pack of 20 pieces for ₹999. Minimum order: 1 pack."});state.heartPhotoDescriptionRevision=1;}
if(state.originalPriceRevision!==1){for(const p of state.products)p.original=Number(p.price)+1000;state.originalPriceRevision=1;}
if(state.heartPriceRevision!==2){const p=state.products.find(p=>p.id==='heart');if(p)Object.assign(p,{price:1199,original:2199,description:'Red lattice heart keychain that can also be filled with toffees and chocolates for gifting. Pack of 20 pieces for ₹1,199. Minimum order: 1 pack.'});state.heartPriceRevision=2;}
// Retire the former sample product from saved storefront state.
const retiredProductIds=new Set(['custom',...state.products.filter(p=>String(p.name||'').trim().toLowerCase()==='custom character concept').map(p=>p.id)]);
state.products=state.products.filter(p=>!retiredProductIds.has(p.id));
for(const id of retiredProductIds)delete state.cart[id];
state.wishlist=state.wishlist.filter(id=>!retiredProductIds.has(id));

if(!state.products.some(p=>p.id==='spiral'))state.products.push({"id":"spiral","name":"Spiral Desk Toy","anime":"Home & Desk","category":"Home & Desk","price":499,"original":1499,"stock":1,"availabilityUnconfirmed":true,"image":"spiral1","images":["spiral1","spiral2","spiral3","spiral4","spiral5"],"colors":["Black","Blue","Red","Yellow","Brown"],"new":true,"featured":true,"height":0,"description":"A geometric spiral desk toy with a layered star-shaped design. Available in Black, Blue, Red, Yellow and Brown. Photos show the design under different lighting. Availability is confirmed by the seller."});
let activeView='home',q='',anime='all',category='all',sort='featured',mode='all',onlyStock=false,max='',coupon='',currentProduct=null,detailQuantity=1,modelUrl,previousFocus,timer;
const $=id=>document.getElementById(id);const photo=p=>ASSETS[p.image]||(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.image||'')?p.image:ASSETS.logo);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Storage unavailable or full. Export your data to keep this session.')}}
function toast(s){$('toast-message').textContent=s;const t=$('toast-notify');t.style.opacity='1';t.style.transform='translateY(0)';clearTimeout(timer);timer=setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(25px)'},4000)}
function modal(title,html){previousFocus=document.activeElement;$('modal-heading').textContent=title;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();document.body.classList.add('modal-open')}
function closeModal(){$('modal').close();document.body.classList.remove('modal-open');previousFocus?.focus?.()}
$('modal').addEventListener('close',()=>{document.body.classList.remove('modal-open');if(modelUrl){URL.revokeObjectURL(modelUrl);modelUrl=null}});
function toggleMenu(b){b.setAttribute('aria-expanded',String($('nav-menu').classList.toggle('mobile-open')))}
const nav=[['home','Home','⌂'],['shop','Shop','♧'],['collections','Collections','▦'],['custom','Custom Figures','⚒'],['drops','New Drops','♨'],['wishlist','Wishlist','♡'],['about','About Us','◇'],['contact','Contact','☏']];
$('side-links').innerHTML=nav.map(([v,l,i])=>`<button class="side-nav-btn" data-view="${v}" title="${l}"><span class="inline-icon">${i}</span><span class="tooltip">${l}</span></button>`).join('');$('nav-menu').innerHTML=nav.filter(n=>!['wishlist','track'].includes(n[0])).map(([v,l])=>`<li><a class="nav-link" href="#${v}" data-view="${v}">${l}</a></li>`).join('');
document.querySelectorAll('[data-asset]').forEach(el=>el.src=ASSETS[el.dataset.asset]);document.documentElement.style.setProperty('--hero-image',`url("${ASSETS.hero}")`);
document.addEventListener('click',e=>{const t=e.target.closest('[data-view]');if(t){e.preventDefault();go(t.dataset.view)}const c=e.target.closest('[data-collection]');if(c){anime=c.dataset.collection;q='';category='all';mode='all';go('shop')}});
function go(view,hash=true){activeView=view;$('nav-menu').classList.remove('mobile-open');document.querySelector('.mobile-toggle')?.setAttribute('aria-expanded','false');if(hash)history.replaceState(null,'','#'+view);$('home-view').hidden=view!=='home';$('page-view').hidden=view==='home';document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='home')featured();else renderPage();window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'home',false));
function card(p){return `<article class="product-card product-card-clickable"><button class="product-details-hit" aria-label="View details for ${E(p.name)}" onclick="details('${p.id}')"></button><div class="product-thumb-wrap"><span class="product-badge">DEMO ${p.new?'· NEW':''}</span><button class="wishlist-toggle" aria-label="Save ${E(p.name)}" onclick="wish('${p.id}')">${state.wishlist.includes(p.id)?'♥':'♡'}</button><img class="product-thumb" loading="lazy" decoding="async" src="${ASSETS[p.image+'Thumb']||photo(p)}" alt="${E(p.name)}"></div><div class="product-body"><span class="anime-series">${E(p.anime)}</span><h3 class="product-title">${E(p.name)}</h3><div class="price-row"><span class="current-price">${INR(p.price)}</span>${p.original>p.price?`<del class="original-price">${INR(p.original)}</del><span class="discount-label">${Math.round(100-p.price/p.original*100)}% OFF</span>`:''}</div><p>${p.availabilityUnconfirmed?'Availability confirmed by seller':p.stock?(p.stock*(p.packSize||1))+' pieces available':'Out of stock'}</p><button class="btn-add-cart" ${p.stock?'':'disabled'} onclick="add('${p.id}')">ADD TO CART</button><small class="demo-tag">${p.minQty?'Per piece · Minimum '+p.minQty+' pieces':p.packSize?'Pack of '+p.packSize+' pieces · '+INR(p.price)+' per pack':p.height?p.height+' cm':''}</small></div></article>`}
function featured(){$('featured-grid').innerHTML=state.products.filter(p=>p.featured).map(card).join('');badge()}
function showShop(m='all'){mode=m;q='';anime='all';category='all';go('shop')}
function opts(list,value){return list.map(v=>`<option value="${E(v)}" ${v===value?'selected':''}>${E(v==='all'?'All':v)}</option>`).join('')}
function shop(){return `<h1>${activeView==='wishlist'?'YOUR WISHLIST':'THE KINGDOM SHOP'}</h1><p>Explore figures, home decor and accessories.</p><div class="catalog-controls"><input id="search" aria-label="Search" placeholder="Search character, anime or product…" value="${E(q)}" oninput="q=this.value;results()"><select aria-label="Anime" onchange="anime=this.value;results()">${opts(['all',...new Set(state.products.map(p=>p.anime))],anime)}</select><select aria-label="Category" onchange="category=this.value;results()">${opts(['all',...new Set(state.products.map(p=>p.category))],category)}</select><select aria-label="Sort" onchange="sort=this.value;results()">${[['featured','Featured'],['new','Newest'],['low','Price: low to high'],['high','Price: high to low'],['name','Name']].map(([v,l])=>`<option value="${v}" ${sort===v?'selected':''}>${l}</option>`).join('')}</select><input aria-label="Maximum price" type="number" min="0" placeholder="Maximum price ₹" value="${E(max)}" oninput="max=this.value;results()"><label><input type="checkbox" ${onlyStock?'checked':''} onchange="onlyStock=this.checked;results()">In stock</label><button class="btn-outline" onclick="q='';anime='all';category='all';mode='all';max='';onlyStock=false;renderPage()">CLEAR FILTERS</button></div><div id="count" class="filter-count"></div><div class="products-grid" id="results"></div>`}
function results(){const list=state.products.filter(p=>(activeView!=='wishlist'||state.wishlist.includes(p.id))&&[p.name,p.anime,p.category,p.id].join(' ').toLowerCase().includes(q.toLowerCase())&&(anime==='all'||anime===p.anime)&&(category==='all'||category===p.category)&&(!max||p.price<=Number(max))&&(!onlyStock||p.stock>0)&&(mode!=='new'||p.new)&&(mode!=='featured'||p.featured)).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name):sort==='new'?Number(b.new)-Number(a.new):Number(b.featured)-Number(a.featured));$('count').textContent=list.length+' products';$('results').innerHTML=list.length?list.map(card).join(''):'<p class="empty-state">No products found. Clear filters or save a figure to your wishlist.</p>'}
function wish(id){state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();toast('Wishlist updated on this browser.');if(activeView==='home')featured();if(['shop','wishlist'].includes(activeView))results()}
function badge(){$('cart-badge-count').textContent=Object.values(state.cart).reduce((a,n)=>a+n,0)}
function add(id,n){const p=state.products.find(p=>p.id===id);if(!p)return;if(p.colors){const choice=$('product-color');if(currentProduct?.id!==id||!choice){details(id);return;}if(!p.colors.includes(choice.value)){toast('Choose a colour.');return;}id=id+'::'+choice.value;}if(n===undefined)n=state.cart[id]?1:(p.minQty||1);if(!Number.isInteger(n)||n<1){toast('Choose a whole quantity.');return}if((state.cart[id]||0)+n<(p.minQty||1)){toast('Minimum order: '+p.minQty+' pieces.');return}if((state.cart[id]||0)+n>p.stock){toast('That quantity is not available.');return}state.cart[id]=(state.cart[id]||0)+n;save();badge();toast('Added to your demo cart.')}
function quantityLabel(p,qty){return p.packSize?qty+' pack'+(qty===1?'':'s')+' · '+(qty*p.packSize)+' pieces':'Qty '+qty}
function orderItem(p,qty){return {id:p.baseId||p.id,...(p.color?{color:p.color}:{}),name:p.name,price:p.price,qty,packSize:p.packSize||1,pieces:qty*(p.packSize||1)}}
function cartProduct(id){const [base,color]=id.split('::');const p=state.products.find(p=>p.id===base);if(!p)return null;if(color){if(!p.colors?.includes(color))return null;return {...p,id,baseId:base,color,name:p.name+' — '+color};}return p;}
function lines(){return Object.entries(state.cart).map(([id,qty])=>({p:cartProduct(id),qty})).filter(x=>x.p&&x.qty>0)}
const COUPONS={RAGGOFAN50OFF:{minimum:799,amount:50},RAGGOFAN100OFF:{minimum:1499,amount:100}};
function applyCoupon(){const code=$('coupon').value.trim().toUpperCase();const offer=COUPONS[code];if(!code){coupon='';openCart();return}if(!offer){toast('Invalid coupon code.');return}const subtotal=lines().reduce((s,{p,qty})=>s+p.price*qty,0);if(subtotal<offer.minimum){toast('Minimum order '+INR(offer.minimum)+' for this coupon.');return}coupon=code;openCart();toast('Coupon applied.')}
function totals(){const subtotal=lines().reduce((s,{p,qty})=>s+p.price*qty,0),discount=COUPONS[coupon]&&subtotal>=COUPONS[coupon].minimum?COUPONS[coupon].amount:0;return {subtotal,discount,shipping:0,total:Math.round((subtotal-discount)*100)/100}}
function summary(){const t=totals();return `<div class="summary-row"><span>Subtotal</span><span>${INR(t.subtotal)}</span></div><div class="summary-row"><span>Shipping</span><span>Free</span></div>${t.discount?`<div class="summary-row"><span>Coupon discount</span><span>−${INR(t.discount)}</span></div>`:''}<div class="summary-row total"><span>Total</span><strong>${INR(t.total)}</strong></div>`}
function change(id,n){const p=cartProduct(id);if(!p)return;if(p.minQty&&(state.cart[id]||0)+n<p.minQty){toast('Minimum order: '+p.minQty+' pieces. Use Remove to delete this item.');return}if((state.cart[id]||0)+n>p.stock){toast('Stock limit reached.');return}state.cart[id]=(state.cart[id]||0)+n;if(state.cart[id]<=0)delete state.cart[id];save();badge();openCart()}
function remove(id){delete state.cart[id];save();badge();openCart()}
function later(id){const base=id.split('::')[0];if(!state.wishlist.includes(base))state.wishlist.push(base);remove(id);toast('Saved to your wishlist.')}
function openCart(){const l=lines();modal('YOUR CART',l.length?l.map(({p,qty})=>`<article class="cart-row"><img src="${photo(p)}" alt="${E(p.name)}"><div><h3>${E(p.name)}</h3><p>${INR(p.price)}${p.packSize?' per pack':''}</p><p>${quantityLabel(p,qty)}</p><button class="text-button" onclick="later('${p.id}')">Save for later</button></div><div><div class="qty"><button aria-label="Decrease quantity" onclick="change('${p.id}',-1)">−</button><span>${qty}</span><button aria-label="Increase quantity" onclick="change('${p.id}',1)">+</button></div><button class="text-button" onclick="remove('${p.id}')">Remove</button></div></article>`).join('')+`<div class="coupon-field"><input id="coupon" aria-label="Coupon code" placeholder="Enter coupon code" value="${E(coupon)}"><button class="btn-outline" onclick="applyCoupon()">APPLY</button></div>${summary()}<p class="viewer-note">Choose Cash on Delivery or UPI at checkout. Orders are submitted to Anime Kingdom.</p><button class="btn-primary" onclick="checkout()">CHECKOUT →</button>`:'<p class="empty-state">Your cart is empty.</p><button class="btn-primary" onclick="closeModal();go(\'shop\')">EXPLORE FIGURES</button>')}
function galleryPhoto(index){const key=currentProduct.images?.[index];if(!key)return;const img=$('detail-main-photo');img.src=photo({...currentProduct,image:key});img.dataset.galleryIndex=String(index);}
function details(id){const p=state.products.find(p=>p.id===id);if(!p)return;currentProduct=p;detailQuantity=p.minQty||1;modal(p.name,`<div class="detail-grid"><div><button style="background:none;border:0;width:100%" aria-label="Zoom photo" onclick="zoomPhoto()"><img id="detail-main-photo" class="detail-photo" src="${photo(p)}" alt="${E(p.name)}"></button>${p.images?.length>1?`<div class="product-gallery">${p.images.map((key,i)=>`<button type="button" aria-label="View photo ${i+1} of ${E(p.name)}" onclick="galleryPhoto(${i})"><img src="${photo({...p,image:key})}" alt="${E(p.name)} — photo ${i+1}"></button>`).join('')}</div>`:''}</div><div class="detail-copy"><span class="anime-series">${E(p.anime)}</span><div class="price-big">${INR(p.price)}${p.minQty?' per piece':''}</div>${p.original>p.price?`<p class="price-row"><del class="original-price">${INR(p.original)}</del><span class="discount-label">${Math.round(100-p.price/p.original*100)}% OFF</span></p>`:''}<p>${E(p.description)}</p>${p.colors?`<label for="product-color">Colour</label><select id="product-color" style="display:block;margin:12px 0;padding:12px;background:#20172e;color:white;border:1px solid #76518d;border-radius:8px;width:100%"><option value="">Select colour</option>${p.colors.map(c=>`<option value="${E(c)}">${E(c)}</option>`).join('')}</select>`:''}${p.packSize?`<p><strong>Pack of ${p.packSize} pieces — ${INR(p.price)}</strong><br>Minimum order: 1 pack (${p.packSize} pieces). Quantity below is the number of packs.</p>`:''}<dl><dt>Height</dt><dd>${p.height?p.height+' cm':'Not supplied'}</dd><dt>Stock</dt><dd>${p.availabilityUnconfirmed?'Confirm with seller':(p.stock*(p.packSize||1))+' pieces available'}</dd></dl><div class="qty"><button aria-label="Decrease quantity" onclick="detailQuantity=Math.max(currentProduct.minQty||1,detailQuantity-1);$('qty').textContent=detailQuantity">−</button><span id="qty">${detailQuantity}</span><button aria-label="Increase quantity" onclick="detailQuantity=Math.min(currentProduct.stock,detailQuantity+1);$('qty').textContent=detailQuantity">+</button></div><div class="detail-buttons"><button class="btn-primary" ${p.stock?'':'disabled'} onclick="add(currentProduct.id,detailQuantity)">ADD TO CART</button><button class="btn-outline" onclick="wish(currentProduct.id)">♡ SAVE</button></div></div></div><h3 style="margin:25px 0">You may also like</h3><div class="detail-buttons">${state.products.filter(x=>x.id!==p.id).slice(0,3).map(x=>`<button class="btn-outline" onclick="details('${x.id}')">${E(x.name)}</button>`).join('')}</div>`)}
function zoomPhoto(){modal(currentProduct.name,`<img class="zoom-photo" src="${$('detail-main-photo')?.src||photo(currentProduct)}" alt="${E(currentProduct.name)}"><button class="btn-outline" onclick="details(currentProduct.id)">BACK TO DETAILS</button>`)}

