const KEY='anime-kingdom-html-demo-v1',E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),INR=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n);
const defaults=[['gojo','Gojo Satoru Figure','Jujutsu Kaisen',2499,12],['spider','Spider-Man Display Figure','Superheroes',2999,8],['hulk','Red Hulk Collectible','Superheroes',3499,5]].map(([id,name,anime,price,stock],i)=>({id,name,anime,price,stock,original:price+500,image:id,category:i===3?'Custom 3D Figures':i===0?'Anime Figures':'Collectibles',new:i===1||i===2,featured:true,material:'Not specified',height:i===1?20:0,description:'Sample listing using a product photograph from your reference website. Price and stock are demonstration values.'}));
let state={products:structuredClone(defaults),cart:{},wishlist:[],orders:[],requests:[],profile:{},dropDate:'',policies:{}};try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.products))state={...state,...s}}catch{}
// Retire the former sample product from saved storefront state.
state.products=state.products.filter(p=>p.id!=='custom');
delete state.cart.custom;
state.wishlist=state.wishlist.filter(id=>id!=='custom');

let activeView='home',q='',anime='all',category='all',sort='featured',mode='all',onlyStock=false,max='',coupon='',currentProduct=null,detailQuantity=1,modelUrl,previousFocus,timer;
const $=id=>document.getElementById(id);const photo=p=>ASSETS[p.image]||(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.image||'')?p.image:ASSETS.logo);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Storage unavailable or full. Export your data to keep this session.')}}
function toast(s){$('toast-message').textContent=s;const t=$('toast-notify');t.style.opacity='1';t.style.transform='translateY(0)';clearTimeout(timer);timer=setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(25px)'},4000)}
function modal(title,html){previousFocus=document.activeElement;$('modal-heading').textContent=title;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();document.body.classList.add('modal-open')}
function closeModal(){$('modal').close();document.body.classList.remove('modal-open');previousFocus?.focus?.()}
$('modal').addEventListener('close',()=>{document.body.classList.remove('modal-open');if(modelUrl){URL.revokeObjectURL(modelUrl);modelUrl=null}});
function toggleMenu(b){b.setAttribute('aria-expanded',String($('nav-menu').classList.toggle('mobile-open')))}
const nav=[['home','Home','⌂'],['shop','Shop','♧'],['collections','Collections','▦'],['custom','Custom Figures','⚒'],['drops','New Drops','♨'],['wishlist','Wishlist','♡'],['about','About Us','◇'],['contact','Contact','☏']];
$('side-links').innerHTML=nav.map(([v,l,i])=>`<button class="side-nav-btn" data-view="${v}" title="${l}"><span class="inline-icon">${i}</span><span class="tooltip">${l}</span></button>`).join('');$('nav-menu').innerHTML=nav.filter(n=>!['wishlist','track'].includes(n[0])).map(([v,l])=>`<li><a class="nav-link" href="#${v}" data-view="${v}">${l}</a></li>`).join('');
document.querySelectorAll('[data-asset]').forEach(el=>el.src=ASSETS[el.dataset.asset]);document.documentElement.style.setProperty('--hero-image',`url("${ASSETS.hero}")`);
document.addEventListener('click',e=>{const t=e.target.closest('[data-view]');if(t){e.preventDefault();go(t.dataset.view)}const c=e.target.closest('[data-collection]');if(c){anime=c.dataset.collection;q='';category='all';mode='all';go('shop')}});
function go(view,hash=true){activeView=view;$('nav-menu').classList.remove('mobile-open');document.querySelector('.mobile-toggle')?.setAttribute('aria-expanded','false');if(hash)history.replaceState(null,'','#'+view);$('home-view').hidden=view!=='home';$('page-view').hidden=view==='home';document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='home')featured();else renderPage();window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'home',false));
function card(p){return `<article class="product-card product-card-clickable"><button class="product-details-hit" aria-label="View details for ${E(p.name)}" onclick="details('${p.id}')"></button><div class="product-thumb-wrap"><span class="product-badge">DEMO ${p.new?'· NEW':''}</span><button class="wishlist-toggle" aria-label="Save ${E(p.name)}" onclick="wish('${p.id}')">${state.wishlist.includes(p.id)?'♥':'♡'}</button><img class="product-thumb" loading="lazy" src="${photo(p)}" alt="${E(p.name)}"></div><div class="product-body"><span class="anime-series">${E(p.anime)}</span><h3 class="product-title">${E(p.name)}</h3><div class="price-row"><span class="current-price">${INR(p.price)}</span>${p.original>p.price?`<del class="original-price">${INR(p.original)}</del><span class="discount-label">${Math.round(100-p.price/p.original*100)}% OFF</span>`:''}</div><p>${p.stock?p.stock+' available in demo':'Out of stock'}</p><button class="btn-add-cart" ${p.stock?'':'disabled'} onclick="add('${p.id}')">ADD TO CART</button><small class="demo-tag">Sample price · No live sales</small></div></article>`}
function featured(){$('featured-grid').innerHTML=state.products.filter(p=>p.featured).map(card).join('');badge()}
function showShop(m='all'){mode=m;q='';anime='all';category='all';go('shop')}
function opts(list,value){return list.map(v=>`<option value="${E(v)}" ${v===value?'selected':''}>${E(v==='all'?'All':v)}</option>`).join('')}
function shop(){return `<h1>${activeView==='wishlist'?'YOUR WISHLIST':'THE KINGDOM SHOP'}</h1><p>Browse the sample collection. Prices and inventory are demo values.</p><div class="catalog-controls"><input id="search" aria-label="Search" placeholder="Search character, anime or product…" value="${E(q)}" oninput="q=this.value;results()"><select aria-label="Anime" onchange="anime=this.value;results()">${opts(['all',...new Set(state.products.map(p=>p.anime))],anime)}</select><select aria-label="Category" onchange="category=this.value;results()">${opts(['all',...new Set(state.products.map(p=>p.category))],category)}</select><select aria-label="Sort" onchange="sort=this.value;results()">${[['featured','Featured'],['new','Newest'],['low','Price: low to high'],['high','Price: high to low'],['name','Name']].map(([v,l])=>`<option value="${v}" ${sort===v?'selected':''}>${l}</option>`).join('')}</select><input aria-label="Maximum price" type="number" min="0" placeholder="Maximum price ₹" value="${E(max)}" oninput="max=this.value;results()"><label><input type="checkbox" ${onlyStock?'checked':''} onchange="onlyStock=this.checked;results()">In stock</label><button class="btn-outline" onclick="q='';anime='all';category='all';mode='all';max='';onlyStock=false;renderPage()">CLEAR FILTERS</button></div><div id="count" class="filter-count"></div><div class="products-grid" id="results"></div>`}
function results(){const list=state.products.filter(p=>(activeView!=='wishlist'||state.wishlist.includes(p.id))&&[p.name,p.anime,p.category,p.id].join(' ').toLowerCase().includes(q.toLowerCase())&&(anime==='all'||anime===p.anime)&&(category==='all'||category===p.category)&&(!max||p.price<=Number(max))&&(!onlyStock||p.stock>0)&&(mode!=='new'||p.new)&&(mode!=='featured'||p.featured)).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name):sort==='new'?Number(b.new)-Number(a.new):Number(b.featured)-Number(a.featured));$('count').textContent=list.length+' products';$('results').innerHTML=list.length?list.map(card).join(''):'<p class="empty-state">No products found. Clear filters or save a figure to your wishlist.</p>'}
function wish(id){state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();toast('Wishlist updated on this browser.');if(activeView==='home')featured();if(['shop','wishlist'].includes(activeView))results()}
function badge(){$('cart-badge-count').textContent=Object.values(state.cart).reduce((a,n)=>a+n,0)}
function add(id,n=1){const p=state.products.find(p=>p.id===id);if(!p)return;if((state.cart[id]||0)+n>p.stock){toast('That quantity is not available.');return}state.cart[id]=(state.cart[id]||0)+n;save();badge();toast('Added to your demo cart.')}
function lines(){return Object.entries(state.cart).map(([id,qty])=>({p:state.products.find(p=>p.id===id),qty})).filter(x=>x.p&&x.qty>0)}
function totals(){const subtotal=lines().reduce((s,{p,qty})=>s+p.price*qty,0),discount=coupon==='KINGDOM10'?Math.round(subtotal*10)/100:0;return {subtotal,discount,shipping:subtotal===0||subtotal>=1999?0:99,total:Math.round((subtotal-discount+(subtotal===0||subtotal>=1999?0:99))*100)/100}}
function summary(){const t=totals();return `<div class="summary-row"><span>Subtotal</span><span>${INR(t.subtotal)}</span></div><div class="summary-row"><span>Demo shipping</span><span>${INR(t.shipping)}</span></div><div class="summary-row"><span>Demo discount</span><span>−${INR(t.discount)}</span></div><div class="summary-row total"><span>Total</span><strong>${INR(t.total)}</strong></div>`}
function change(id,n){const p=state.products.find(p=>p.id===id);if((state.cart[id]||0)+n>p.stock){toast('Stock limit reached.');return}state.cart[id]=(state.cart[id]||0)+n;if(state.cart[id]<=0)delete state.cart[id];save();badge();openCart()}
function remove(id){delete state.cart[id];save();badge();openCart()}
function later(id){if(!state.wishlist.includes(id))state.wishlist.push(id);remove(id);toast('Saved to your wishlist.')}
function openCart(){const l=lines();modal('YOUR CART',l.length?l.map(({p,qty})=>`<article class="cart-row"><img src="${photo(p)}" alt="${E(p.name)}"><div><h3>${E(p.name)}</h3><p>${INR(p.price)} · Demo</p><button class="text-button" onclick="later('${p.id}')">Save for later</button></div><div><div class="qty"><button aria-label="Decrease quantity" onclick="change('${p.id}',-1)">−</button><span>${qty}</span><button aria-label="Increase quantity" onclick="change('${p.id}',1)">+</button></div><button class="text-button" onclick="remove('${p.id}')">Remove</button></div></article>`).join('')+`<div class="coupon-field"><input id="coupon" aria-label="Coupon" placeholder="Demo coupon: KINGDOM10" value="${E(coupon)}"><button class="btn-outline" onclick="applyCoupon()">APPLY</button></div>${summary()}<p class="viewer-note">Choose Cash on Delivery or UPI at checkout. Orders are submitted to Anime Kingdom.</p><button class="btn-primary" onclick="checkout()">CHECKOUT →</button>`:'<p class="empty-state">Your cart is empty.</p><button class="btn-primary" onclick="closeModal();go(\'shop\')">EXPLORE FIGURES</button>')}
function applyCoupon(){const c=$('coupon').value.trim().toUpperCase();if(c&&c!=='KINGDOM10'){toast('Invalid demo coupon. Try KINGDOM10.');return}coupon=c;openCart();toast(c?'Demo discount applied.':'Coupon removed.')}
function details(id){const p=state.products.find(p=>p.id===id);if(!p)return;currentProduct=p;detailQuantity=1;modal(p.name,`<div class="detail-grid"><button style="background:none;border:0" aria-label="Zoom photo" onclick="zoomPhoto()"><img class="detail-photo" src="${photo(p)}" alt="${E(p.name)}"></button><div class="detail-copy"><span class="anime-series">${E(p.anime)}</span><div class="price-big">${INR(p.price)}</div><p>${E(p.description)}</p><dl><dt>Material</dt><dd>${E(p.material)}</dd><dt>Height</dt><dd>${p.height?p.height+' cm':'Not supplied'}</dd><dt>Stock</dt><dd>${p.stock} demo units</dd></dl><div class="qty"><button aria-label="Decrease quantity" onclick="detailQuantity=Math.max(1,detailQuantity-1);$('qty').textContent=detailQuantity">−</button><span id="qty">1</span><button aria-label="Increase quantity" onclick="detailQuantity=Math.min(currentProduct.stock,detailQuantity+1);$('qty').textContent=detailQuantity">+</button></div><div class="detail-buttons"><button class="btn-primary" ${p.stock?'':'disabled'} onclick="add(currentProduct.id,detailQuantity)">ADD TO CART</button><button class="btn-outline" onclick="wish(currentProduct.id)">♡ SAVE</button></div><p>Live delivery and return terms are not configured. Verified reviews require a purchase-verification backend; no ratings are invented here.</p></div></div><h3 style="margin:25px 0">You may also like</h3><div class="detail-buttons">${state.products.filter(x=>x.id!==p.id).slice(0,3).map(x=>`<button class="btn-outline" onclick="details('${x.id}')">${E(x.name)}</button>`).join('')}</div>`)}
function zoomPhoto(){modal(currentProduct.name,`<img class="zoom-photo" src="${photo(currentProduct)}" alt="${E(currentProduct.name)}"><button class="btn-outline" onclick="details(currentProduct.id)">BACK TO DETAILS</button>`)}

