import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const html=fs.readFileSync('outputs/anime-kingdom.html','utf8');
const script=fs.readFileSync('public/storefront/app.js','utf8');
const nodes=new Map();const node=()=>({innerHTML:'',textContent:'',value:'',hidden:false,open:false,style:{setProperty(){}},classList:{add(){},remove(){},toggle(){return false}},setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},focus(){},appendChild(){},replaceChildren(){},remove(){},click(){}});
const get=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)};
const context=vm.createContext({console,Intl,Date,Math,JSON,Number,String,Object,Array,Set,Map,Promise,RegExp,Uint8Array,DataView,structuredClone,crypto:webcrypto,ASSETS:{},localStorage:{getItem(){return null},setItem(){}},document:{getElementById:get,querySelectorAll(){return []},querySelector(){return node()},addEventListener(){},createElement:node,documentElement:node(),body:node(),activeElement:node()},window:{addEventListener(){},scrollTo(){}},history:{replaceState(){}},location:{hash:''},setTimeout(){return 1},clearTimeout(){},setInterval(){},URL,Blob,FormData:class{constructor(value){this.data=value}entries(){return Object.entries(this.data)}[Symbol.iterator](){return this.entries()[Symbol.iterator]()}}});
vm.runInContext(script,context);
const run=s=>vm.runInContext(s,context);

let requests=[];context.AbortSignal=AbortSignal;
context.fetch=async(url,options)=>{requests.push({url,options});return {ok:false,status:403,json:async()=>({code:'42501'})}};
context.mockForm={dataset:{},reportValidity:()=>true,querySelectorAll:()=>[],name:'Integration Test',email:'test@example.com',phone:'9000000000',address:'Test address',city:'Test city',state:'Test state',pin:'110001',payment:'cod'};
context.FormData=class{constructor(f){this.f=f}[Symbol.iterator](){return Object.entries(this.f).filter(([k,v])=>typeof v==='string')[Symbol.iterator]()}};
run("add('gojo',1)");
assert.equal(run('totals().shipping'),0);assert.equal(run('totals().total'),999);
await run('placeOrder({preventDefault(){},target:mockForm})');
assert.equal(run('state.orders.length'),0);assert.equal(run('state.cart.gojo'),1);
assert.notEqual(get('modal-heading').textContent,'Thank you for your order!');
context.fetch=async(url,options)=>{requests.push({url,options});return {ok:true,status:201}};
await run('placeOrder({preventDefault(){},target:mockForm})');
assert.equal(run('state.orders.length'),1);assert.equal(run('Object.keys(state.cart).length'),0);assert.equal(run('state.orders[0].cloudSaved'),true);
assert.equal(get('modal-heading').textContent,'Thank you for your order!');assert.equal(get('modal').open,true);assert.ok(get('modal-body').innerHTML.includes(run('state.orders[0].id')));
const row=JSON.parse(requests.at(-1).options.body);assert.equal(row.customer_name,'Integration Test');assert.equal(row.form_data.address.pin,'110001');assert.equal(row.form_data.items[0].id,'gojo');assert.equal(row.status,'pending');assert.equal(row.payment_method,'cod');
assert.equal(JSON.parse(requests[0].options.body).id,row.id);
assert.equal(requests.at(-1).options.headers.apikey.startsWith('sb_publishable_'),true);
console.log('PASS: rejected submissions retain cart; successful submission saves receipt, full details, pending status, and stable retry ID.');
// Pack quantities must remain whole packs, with piece counts saved alongside them.
run("state.products.push({id:'test-pack',name:'Test pack',price:999,stock:10,packSize:20,image:'logo'});state.cart={};add('test-pack',1)");
assert.equal(run('totals().subtotal'),999);
assert.equal(run("quantityLabel(state.products.find(p=>p.id==='test-pack'),1)"),'1 pack · 20 pieces');
run("add('test-pack',0.5)");assert.equal(run("state.cart['test-pack']"),1);
run("add('test-pack',1)");assert.equal(run('totals().subtotal'),1998);
const pack=JSON.parse(run("JSON.stringify(orderItem(state.products.find(p=>p.id==='test-pack'),2))"));
assert.equal(pack.qty,2);assert.equal(pack.pieces,40);assert.equal(pack.packSize,20);
console.log('PASS: 20-piece packs cost 999 per pack; fractional packs rejected; receipt metadata preserves 40 pieces for two packs.');
run("state.cart={};coupon='';add('heart')");
assert.equal(run('state.cart.heart'),20);assert.equal(run('totals().total'),1000);
run("change('heart',-1)");assert.equal(run('state.cart.heart'),20);
run("add('heart',380)");assert.equal(run('state.cart.heart'),400);
run("add('heart',1)");assert.equal(run('state.cart.heart'),400);
run("state.cart={};add('heart',19)");assert.equal(run('state.cart.heart'),undefined);
console.log('PASS: heart minimum is 20 pieces at 1000; stock capped at 400.');
