import fs from 'node:fs';
let p=fs.readFileSync('work/export-pages.js','utf8');
p=p.replace(/^(?:async )?function (placeOrder|contactDraft|saveCustom)\(.*\r?\n/gm,'');
p=p.replace('onsubmit="event.preventDefault();state.profile=Object.fromEntries(new FormData(this));save();toast(\'Profile saved locally.\')"','onsubmit="saveProfile(event)"');
p=p.replace('SAVE LOCAL PROFILE','SAVE CUSTOMER DETAILS').replace('MY DEMO ACCOUNT','CUSTOMER DETAILS').replace('This is a local profile, not secure authentication. Use sample details.','Send your contact and delivery details to Anime Kingdom. This form does not create a login account.');
p=p.replace('Create and download a concept brief. This does not submit a request or place a live order.','Send your concept brief to Anime Kingdom for review. A custom request is not a confirmed purchase.');
p=p.replace('<form class="ak-form" onsubmit="saveCustom(event)">','<form class="ak-form" onsubmit="saveCustom(event)"><label>Full name<input name="name" required maxlength="300"></label><label>Email<input name="email" type="email" required maxlength="320"></label><label>Phone<input name="phone" type="tel" required pattern="[6-9][0-9]{9}"></label>');
p=p.replace('Reference image (local only)','Reference image').replace('SAVE & DOWNLOAD BRIEF','SUBMIT CUSTOM REQUEST');
p=p.replace('Local draft — not submitted',"${r.cloudSaved?'Submitted to Anime Kingdom':'Local draft — not submitted'}");
p=p.replace('DOWNLOAD CONTACT DRAFT','SEND MESSAGE').replace('No message is sent automatically.','Your submitted message is stored privately in Anime Kingdom’s database.');
p=p.replace('Your UTR and screenshot are saved on this device only.','Your UTR and screenshot are sent privately to Anime Kingdom for verification.');
p=p.replace('This standalone file saves your order on this device only. It does not send it to the seller or arrange delivery. Confirm the order and amount with the seller before transferring money.','Your order, address and payment proof are sent to Anime Kingdom. Submission is confirmed only after the database saves it. Payment verification and delivery confirmation are handled by the seller.');
p=p.replaceAll('SAVE COD ORDER','PLACE COD ORDER').replaceAll('SAVE ORDER · VERIFICATION PENDING','SUBMIT ORDER · VERIFICATION PENDING');
p=p.replace('Orders saved on this device. Contact the seller to confirm your order.','New orders are submitted to Anime Kingdom. This page shows your receipts on this device.');
p=p.replace('Local simulation: ${E(o.status)}. No courier connected.',"${o.cloudSaved?'Received by Anime Kingdom. Awaiting seller confirmation.':'Older local-only order; not submitted to the seller.'}");
p=p.replace('DOWNLOAD DEMO INVOICE','DOWNLOAD ORDER RECEIPT');
p=p.replace('TEST ORDER — NOT A TAX INVOICE',"${o.cloudSaved?'ORDER RECEIPT — NOT A TAX INVOICE':'LOCAL TEST ORDER — NOT A TAX INVOICE'}");
p=p.replace('Order saved locally; seller confirmation required.',"${o.cloudSaved?'Order received in Anime Kingdom database; seller confirmation required.':'Order saved locally only; not submitted.'}");
p=p.replace('This HTML demo stores cart, wishlist, sample profile, custom briefs and test orders in this browser. Do not enter payment data. No form submits to a server. Instagram opens an external service. Export or reset data in the local editor.','Submitted orders, contact details, addresses, custom briefs, UTR numbers and payment screenshots are stored privately in Anime Kingdom’s Supabase database. Cart, wishlist and receipt copies are kept on this device. Never enter card details, passwords or UPI PINs. Contact the store for data removal.');
p=p.replace('This is a demonstration, not a live selling service. Prices, stock and order states are samples. No payment is processed or transaction accepted. Final business terms must be supplied before launch.','Submitted orders are pending seller review. Catalog prices and stock are samples until confirmed by the store. UPI transfers are made in your payment app and require manual verification. Delivery and final business terms require seller confirmation.');
p=p.replace('No. This is a standalone HTML demo. No payment or shipment occurs.','The forms send submissions to Anime Kingdom. Orders, prices and delivery still require seller confirmation.');
p=p.replace('Save a downloadable brief with size, pose, accessories and a reference photo. It is not submitted automatically.','Submit a brief with size, pose, accessories and a reference photo for seller review.');
fs.writeFileSync('work/export-pages.js',p);
let c=fs.readFileSync('work/export-core.js','utf8').replace('Orders are saved on this device.','Orders are submitted to Anime Kingdom.');fs.writeFileSync('work/export-core.js',c);
let b=fs.readFileSync('work/build-html-export.mjs','utf8').replace("'work/export-editor.js'","'work/export-editor.js','work/export-supabase.js'");fs.writeFileSync('work/build-html-export.mjs',b);
